### PR TITLE
Added support for selecting javax.swing.JList items by text.

### PR DESCRIPTION
**Pull request by kabroadb**
I added support for finding JList items by their text. It will work if the default cell renderer is used. It has been tested with both single and multi-column lists.

I added a sample (src/test/groovy/com/athaydes/automaton/samples/JListSample.groovy) where JList items in a list with three columns are being clicked on using a text selector.

### CODE REVIEW

**Comment by meyertee** [comment]
Would love to use this too! @renatoathaydes , did you have any thoughts on merging this?

**Comment by renatoathaydes** [comment]
@meyertee yeah, of course! I've been pretty busy with other projects and left this a little abandoned for a while... I am planning to get more active on this again soon. Will merge this PR as soon as I can.

**Comment by renatoathaydes** [comment]
Version 1.2.3 was just released and includes this contribution. Thank you again!

**Comment by meyertee** [comment]
That was fast, many thanks to the both of you!

**Pull request merged**
