### PR TITLE
Release 1.3.1-beta

### PR DESCRIPTION
**Pull request by renatoathaydes**
These are all the changes for the release of Automaton `1.3.1-beta`.

I would like to ask as many people as possible to please test this version with their projects and let me know by commenting on this PR if everything is still working well for their projects.

The reason I ask this is that this version, Automaton's first ever Beta, has a lot of improvements, bug fixes and performance-wise, but some small breaking changes that I don't expect will affect many people.... but given that Automaton has been downloaded quite a lot lately, I want to play safe.

Hope everyone who has been using Automaton can help me out with this.

Cheers!

### CODE REVIEW

**Comment by renatoathaydes** [comment]
If you have tried the beta but you couldn't compile because [swing-selectors](https://github.com/renatoathaydes/swing-selectors) could not be found, that's because I split off the Swing Selectors from Automaton into its own library, which is also hosted on JCenter but is waiting for approval. Should be ready in a few hours.

**Comment by meyertee** [comment]
I just tried to use the beta as dependency in my gradle build file, but it seems that the beta depends on `swing-selectors:1.0-SNAPSHOT` while only `swing-selectors:1.0` is published to [jcenter](http://jcenter.bintray.com/com/athaydes/automaton/swing-selectors/).

To work around the issue I replaced the version in build.gradle:
```
configurations.all {
  resolutionStrategy.eachDependency { DependencyResolveDetails details ->
    if (details.requested.group == 'com.athaydes.automaton' && details.requested.name == 'swing-selectors' && details.requested.version == '1.0-SNAPSHOT') {
      details.useVersion '1.0'
    }
  }
}
```

Good news are, all my tests passed!
It's a Swing project, not a huge amount of tests (~200 tests, maybe half of them using Automaton) using various kinds of selection and interaction on text fields, labels, lists, comboboxes, dialogs.

I also checked out the externalize-selectors branch and let the Automaton tests run (on OS X 10.10.5, Java 1.8.0_60) and had 17 failures. Most of them seem unrelated to the changes, mostly `java.util.concurrent.TimeoutException` and I could see the mouse moving around without any components visible for example. I can send you the test report if you like.

Thank you for your work!

**Comment by renatoathaydes** [comment]
Hi @meyertee Thanks very much for the feedback. I can't believe I published the beta version depending on the SNAPSHOT!!! Thanks for finding that out :) Will fix that ASAP.

One thing I don't understand is how your tests pass with the beta version but not with this branch... the two should be the same!? I mean, I published the beta version off this branch...

Anyway, if you think it's nothing related to the changes in this branch, then I feel pretty confident this version is good to merge to master soon...

**Comment by renatoathaydes** [comment]
Published version 1.3.1-beta with the fixed dependency.

**Comment by meyertee** [comment]
Hi, thanks for the update!
Sorry, misunderstanding.. I meant the tests of Automaton itself produced some failures, I cloned your repo and executed `./gradlew test` in it. I never tried that before on the master branch and I assume they'd fail there too, that's why I think they're unrelated.
The tests of my own project ran without a problem with the beta.

**Comment by renatoathaydes** [comment]
Ah, ok... the tests normally fail due to some large delays that happen for some reason. I usually run the tests in separate groups, then they all pass.

I'm still trying to figure out how to fix this! Thanks for the feedback again.

**Pull request merged**
